# Working Example

A major Non-Governmental Organization is implementing a Social Safety Net program providing Cash Assistance to 2076 beneficiaries. The aim of providing the cash assistance is to assist beneficiary households as follows:

1.	Improve their income gap (Total_income – Total_expenditure), 
2.	Reduce their total debt
3.	Decrease their Livelihood Coping Strategy Index-LCSI (this measures household long term coping capabilities)
4.	Decrease their Reduced Coping Strategy Index- rCSI (this measures households short term food security. 
5.	Improve Food Consumption Scores - FCS
6. Poor FCG = FCS<25, Boderline FCS= 26-45 FCS, Acceptable FCG = FCS>45

To understand the effectiveness in meeting the objectives above, the program set a group of 1895 households, not receiving the cash assistance, whose results on income gap, total debt, LCSI, FCS and rCSI were to be compared with those of the 2076 beneficiaries provided with cash assistance. The households receiving Cash assistance were the Intervention group and those not receiving cash assistance were the Control group . Baseline data was collected before the Cash assistance was provided and after 3 years of receiving cash assistance Endline data was also collected from both the intervention and the Control groups.

The CTP_BaselineEndline.csv contains this data.

In [4]:
import pandas as pd
import numpy as np

Importing the dataset

In [5]:
data = pd.read_csv("CTP_BaselineEndline.csv")

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7942 entries, 0 to 7941
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   HHD_id             7942 non-null   object
 1   Program_level      7942 non-null   object
 2   BenefStatus        7942 non-null   object
 3   AgeHH              7942 non-null   int64
 4   HHsize             7942 non-null   int64
 5   Total_Expenditure  7942 non-null   int64
 6   Total_Income       7942 non-null   int64
 7   Total_debt         7942 non-null   float64
 8   FCS                7942 non-null   float64
 9   FCG                7942 non-null   object
 10  LCSI               7942 non-null   float64
 11  rCSI               7942 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 744.7+ KB

In [7]:
data.head()

,HHD_id,Program_level,BenefStatus,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt,FCS,FCG,LCSI,rCSI
0,SA24354,Baseline,Beneficiary,30,5,1682,1800,0.0,56.0,acceptable,0.0,0.0
1,SA27827,Baseline,Non-Beneficiary,19,5,1268,2500,5000.0,37.0,borderline,4.0,7.0
2,SA24800,Baseline,Beneficiary,33,2,1239,0,500.0,27.0,poor,6.0,7.0
3,SA25314,Baseline,Beneficiary,38,9,2828,2000,100.0,69.0,acceptable,1.0,7.0
4,SA25318,Baseline,Beneficiary,44,10,3403,2950,1000.0,43.0,acceptable,8.0,7.0

## Measures of Central Tendencies

A measure of central tendency is a single value that attempts to describe a set of data by identifying the central position within that set of data. 
They include: Mean, Median and Mode
    Median are mostly preferred when describing data that tends to have outliers, such as as Currency related data such as Income, Expenditure and Debt
    Mean is used to describe variables that tend to have a normal distribution such as Age
    Mode is used to describe variables whose outcomes are count such as Number of people in a household

In [8]:
# creating Baseline and endline samples for beneficiaries and non-beneficiaries

Baseline= data[data["Program_level"]=="Baseline"]
Endline = data[data["Program_level"]=="Endline"]
BenefBaseline= Baseline[Baseline["BenefStatus"]=="Beneficiary"]
NonBenefBaseline= Baseline[Baseline["BenefStatus"]=="Non-Beneficiary"]
BenefEndline= Endline[Endline["BenefStatus"]=="Beneficiary"]
NonBenefEndline= Endline[Endline["BenefStatus"]=="Non-Beneficiary"]

##### Descriptive Statistics

In [9]:
# Descriptive statistics for beneficiaries at baseline

BenefBaseline.describe()

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt,FCS,LCSI,rCSI
count,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000
mean,38.021195,6.473988,2763.265414,1373.073218,1824.458574,59.055877,4.042389,10.312139
std,10.250291,2.337911,1109.266911,956.889953,2778.934553,18.181866,2.878442,9.130849
min,19.000000,1.000000,469.000000,0.000000,0.000000,21.000000,0.000000,0.000000
25%,31.000000,5.000000,2028.500000,700.000000,100.000000,44.500000,2.000000,4.000000
50%,36.000000,6.000000,2600.500000,1400.000000,1000.000000,58.000000,4.000000,7.000000
75%,43.000000,8.000000,3303.000000,2000.000000,2500.000000,72.000000,6.000000,14.000000
max,90.000000,20.000000,17755.000000,8000.000000,35000.000000,112.000000,16.000000,50.000000

In [10]:
#Descriptive statistics for beneficiaries at endline

BenefEndline.describe()

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt,FCS,LCSI,rCSI
count,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000
mean,41.021195,6.473988,3039.641137,1510.383911,2006.904432,53.187861,4.446628,11.343353
std,10.250291,2.337911,1220.189316,1052.577027,3056.828008,16.351835,3.166287,10.043934
min,22.000000,1.000000,516.000000,0.000000,0.000000,19.000000,0.000000,0.000000
25%,34.000000,5.000000,2231.500000,770.000000,110.000000,40.000000,2.200000,4.400000
50%,39.000000,6.000000,2860.500000,1540.000000,1100.000000,52.000000,4.400000,7.700000
75%,46.000000,8.000000,3633.000000,2200.000000,2750.000000,65.000000,6.600000,15.400000
max,93.000000,20.000000,19531.000000,8800.000000,38500.000000,101.000000,17.600000,55.000000

In [11]:
# Descriptive statistics for non-beneficiaries at baseline

NonBenefBaseline.describe()

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt,FCS,LCSI,rCSI
count,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000
mean,38.872296,4.911873,2610.967282,1789.863852,2417.543008,58.572559,4.061741,10.396834
std,12.337499,2.026525,1260.129774,1231.158532,7711.377084,18.693080,2.865866,9.629065
min,18.000000,1.000000,260.000000,0.000000,0.000000,18.500000,0.000000,0.000000
25%,28.500000,4.000000,1865.500000,1100.000000,0.000000,43.000000,2.000000,3.000000
50%,37.000000,4.000000,2372.000000,1700.000000,1000.000000,58.000000,4.000000,7.000000
75%,49.000000,6.000000,3069.500000,2200.000000,2900.000000,71.000000,6.000000,14.000000
max,85.000000,20.000000,22906.000000,24600.000000,200000.000000,112.000000,15.000000,56.000000

In [12]:
# Descriptive statistics for non-beneficiaries at endline

NonBenefEndline.describe()

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt,FCS,LCSI,rCSI
count,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000,1895.000000
mean,41.872296,4.911873,2872.093931,1968.854881,2659.297309,52.758839,4.467916,11.436517
std,12.337499,2.026525,1386.145538,1354.273241,8482.514792,16.828422,3.152452,10.591971
min,21.000000,1.000000,286.000000,0.000000,0.000000,17.000000,0.000000,0.000000
25%,31.500000,4.000000,2052.000000,1210.000000,0.000000,39.000000,2.200000,3.300000
50%,40.000000,4.000000,2609.000000,1870.000000,1100.000000,52.000000,4.400000,7.700000
75%,52.000000,6.000000,3376.500000,2420.000000,3190.000000,64.000000,6.600000,15.400000
max,88.000000,20.000000,25197.000000,27060.000000,220000.000000,101.000000,16.500000,61.600000

##### Measures of central tendencies

In [13]:
# Presenting the mean Age, mode Household size, Median Total Expenditure, Median Total income and Median debt, at endline

Endline.groupby("BenefStatus").agg({"AgeHH":"mean","HHsize":pd.Series.mode,"Total_Expenditure":"median","Total_Income":"median","Total_debt":"median"})

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt
BenefStatus,,,,,
Beneficiary,41.021195,5,2860.5,1540.0,1100.0
Non-Beneficiary,41.872296,4,2609.0,1870.0,1100.0

In [14]:
# Presenting the mean Age, mode Household size, Median Total Expenditure, Median Total income and Median debt, at baseline

Baseline.groupby("BenefStatus").agg({"AgeHH":"mean","HHsize":pd.Series.mode,"Total_Expenditure":"median","Total_Income":"median","Total_debt":"median"})

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt
BenefStatus,,,,,
Beneficiary,38.021195,5,2600.5,1400.0,1000.0
Non-Beneficiary,38.872296,4,2372.0,1700.0,1000.0

## One Sample T-Test

The one-sample t-test is used when you have data from a single sample of participants and you wish to know whether the mean of the sample is the same as the hypothesized mean.

The project had set the following targets to be achieved at endline.

Total Expenditure = 300
Total Income = 160
Total Debt = 190

We will use the one sample T-Test to test whether at endline the project managed to achieve its targets at 95% confidence levels

In [15]:
BenefEndline.describe()

,AgeHH,HHsize,Total_Expenditure,Total_Income,Total_debt,FCS,LCSI,rCSI
count,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000,2076.000000
mean,41.021195,6.473988,3039.641137,1510.383911,2006.904432,53.187861,4.446628,11.343353
std,10.250291,2.337911,1220.189316,1052.577027,3056.828008,16.351835,3.166287,10.043934
min,22.000000,1.000000,516.000000,0.000000,0.000000,19.000000,0.000000,0.000000
25%,34.000000,5.000000,2231.500000,770.000000,110.000000,40.000000,2.200000,4.400000
50%,39.000000,6.000000,2860.500000,1540.000000,1100.000000,52.000000,4.400000,7.700000
75%,46.000000,8.000000,3633.000000,2200.000000,2750.000000,65.000000,6.600000,15.400000
max,93.000000,20.000000,19531.000000,8800.000000,38500.000000,101.000000,17.600000,55.000000

1. Performing a one sample t-test to test if the sample mean of 3039.641137 for Total_Expenditure at endline is not different from the Targeted value of 3000

Null Hypothesis: The sample mean and the projected mean are not different
Alternative Hypothesis: The sample mean and the projected mean were different

In [16]:
# Conducting the one sample T Test on Total expenditure

In [17]:
import scipy.stats as stats
t_statistic, p_value = stats.ttest_1samp(a=BenefEndline['Total_Expenditure'], popmean=3000)
print(t_statistic , p_value)

1.480241434978882 0.13896063568146047

Conclusion: 
The P-Value is greater than 0.05 and we therefore fail to reject the null hypothesis and conclude that the total expenditure from the sample and the projected target are not different

The project therefore met its target of 3000 at 95% confidence levels

In [18]:
# Conducting the one sample T Test on Total Income

2. Performing a one sample t-test to test if the sample mean of 1510.383911 for Total_Income at endline is not different from the Targeted value of 1600

Null Hypothesis: The sample mean and the projected mean are not different
Alternative Hypothesis: The sample mean and the projected mean were different

In [19]:
t_statistic, p_value = stats.ttest_1samp(a=BenefEndline['Total_Income'], popmean=1600)
print(t_statistic , p_value)

-3.8792321673096013 0.00010805225657345563

Conclusion: 
The P-Value is less than 0.05 and we therefore reject the null hypothesis and conclude that the total income from the sample and the project target are different

At 95% confidence levels, the project therefore did not meet its target of household income of 1600

In [20]:
# perform one sample t-test on Total_debt

3. Performing a one sample t-test to test if the sample mean of 2006.904432 for Total_debt at endline is not different from the Targeted value of 1500

Null Hypothesis: The sample mean and the projected mean are not different
Alternative Hypothesis: The sample mean and the projected mean were different

In [21]:
t_statistic, p_value = stats.ttest_1samp(a=BenefEndline['Total_debt'], popmean=1500)
print(t_statistic , p_value)

7.555596534793151 6.214176943231519e-14

Conclusion: 
The P-Value is less than 0.05 and we therefore reject the null hypothesis and conclude that the total debt from the sample and the project target are different

At 95% confidence levels, the project therefore did not meet its target for household debt of 1500

# T-test with more than one sample

In the previous section, a One-Sample T-test was used to determine whether a single sample mean was equal to a hypothesized mean. This section will extend the understanding of sampling distributions to ask whether two sets of samples are random sample from the same population (i.e. the means of the different samples are the same). If they are random samples from the same population, then any differences across conditions or groups can be attributed to random sampling variability. However if the two sets of scores are random sample from different populations, then you can attribute any difference between to the treatment effect (in our case the treatment effect is the Cash transfer program).

### Repeated-measures t-test

The repeated measures t-test, also referred to as the dependent-samples or paired-t-test, is used when you have data from only one group of participants, in other words, an individual obtain two scores  under different levels of the independent variable. Data that are collected from the same group of participant are also referred to as within-subjects, because the same subject performed in the same conditions. Studies which employ a pretest posttest design are commonly analyzed using repeated – measures t-tests. In this form of design, the same participant obtains the score of pretest and after some intervention, a score on the posttest. You wish to determine whether the intervention has an impact by assessing the difference between means of the two sets of scores.

In our example,
We want to test whether the FCS (Food Consumption Scores) changed at endline compared to baseline only for the beneficiaries
    we set the following Hypothesis:
        Null Hypothesis: At 95% confidence levels ,the difference in beneficiary mean in FCS for at baseline and endline is not significant
        Alternative #Hypothesis: At 95% confidence levels, the difference in beneficiary mean in FCS for at baseline and endline is significant

In [22]:
# Extract the sample of beneficiaries only at Baseline
BenefBaseline= Baseline[Baseline["BenefStatus"]=="Beneficiary"]

In [23]:
print(BenefBaseline["FCS"].mean(),BenefEndline["FCS"].mean())

59.05587668593449 53.1878612716763

In [24]:
BenefBaseline["FCS"].mean()-BenefEndline["FCS"].mean()

5.8680154142581955

The food consumption score reduced by approximately 5.86 from at Endline compared to Baseline, we now use the repeated measure T-Test to check if this difference between baseline and endline is significant

In [25]:
stats.ttest_rel(BenefBaseline["FCS"],BenefEndline["FCS"])

TtestResult(statistic=144.15027365037272, pvalue=0.0, df=2075)

Conclusion:
    The p value is less than 0.05, this means we reject the null hypothesis and we conclude that even though the project aimed to improve the food consumption scores, the Food Consumption Scores reduced significantly and so the project was ineffective in reducing FCS.

### The independent-groups t-test

The independent-groups t-test is appropriate when the different participants have performed in each of the different conditions; in other words, when the participants in one condition are different from the participants in the other condition. This is commonly referred to as a between- subjects design.

The hypothesis of the independent groups T-test are as follows:
    Null Hypothesis: There is no difference in the mean of the two groups
    Alternative Hypothesis: There is a difference in the means of the two groups

if the P value of the test is less than 0.05, we reject the Null hypothesis at 95% confidence levels and accepct the alternative hypothesis

##### Getting the descriptive statistics of LCSI for beneficiaries and non beneficiaries at endline

In [26]:
NonBenefEndline["LCSI"].describe()

count    1895.000000
mean        4.467916
std         3.152452
min         0.000000
25%         2.200000
50%         4.400000
75%         6.600000
max        16.500000
Name: LCSI, dtype: float64

In [27]:
BenefEndline["LCSI"].describe()

count    2076.000000
mean        4.446628
std         3.166287
min         0.000000
25%         2.200000
50%         4.400000
75%         6.600000
max        17.600000
Name: LCSI, dtype: float64

##### Running the independent sample T-Test

Running the independent sample T-Test to compare the difference in means of FCS for the Beneficiaries and Non beneficiaries samples
    Null hypothesis: the mean of the two samples are not different (i.e. the program was not effective in improving the FSC of those receiving Cash)
    Alternative hypothesis: the mean of the two samples are different (i.e. the program was effective in improving the FCS of those receiving the cash assistance to be different from those not receiving)

In [28]:
# running the independent sample T-Test
stats.ttest_ind(NonBenefEndline["LCSI"],BenefEndline["LCSI"], equal_var=True)

Ttest_indResult(statistic=0.2120541944265951, pvalue=0.832075643085827)

Conclusion:
    The p-value is greater than 0.05, we therefore fail the null hypothesis and conclude that the program was not effective in improving the FSC of those receiving Cash assistance